### ISSUE TITLE
Returning strings for use in element attributes such as placeholder

### ISSUE THREAD

**Issue by Cookst3r** [ryandrewjohnson/react-localize-redux#146] opened 2019-02-11 10:06 UTC
Advice/Information/Feature

**Unable to return text for placeholders**
React 16+ react-localize-redux 3.5+

I am trying to return a localised string for use as a placeholder in a text box;

```ts
<TextBox
 placeholder={translate.....}
/>
```

Is this possible? If so please advise as to the method.

I am not using redux for localisation in this project

**Comment by ryandrewjohnson** [comment] 2019-02-12 03:20
Duplicate of #145

**Closed by ryandrewjohnson** 2019-02-12 03:20 UTC
