### ISSUE TITLE
Pull String from translation

### ISSUE THREAD

**Issue by tabaktoni** [ryandrewjohnson/react-localize-redux#120] opened 2018-08-27 09:11 UTC
I use Ant Design lib. In some casis i need to pull only string from translation not react object. For ex. placeholder component parameters for translation and so on. It will be good to be able to pull just string. I try with Translate({id:'key'}) but it return react object also.

**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

**Which versions of `react` and `react-localize-redux` are you using?**

**Comment by thchia** [comment] 2018-09-11 06:56
> I try with Translate({id:'key'}) but it return react object also

Do you mean you tried the following:

```jsx
<Translate>
  {({ translate }) => <input placeholder={translate('greeting')} />}
</Translate>
```

This would be the recommended way to get a string, and as far as I can tell should work. If it does not, please provide a reproduction.

**Comment by arturgithub** [comment] 2018-09-22 15:30
Hi,

I was facing the exact same situation with Ant design and placeholders and that solved the issue indeed.

Thanks,

**Comment by ryandrewjohnson** [comment] 2018-11-06 18:16
Closing since it looks like @thchia answered the question.

**Closed by ryandrewjohnson** 2018-11-06 18:16 UTC
Labels: bug
