### ISSUE TITLE
Extremely Slow when a language file is getting large 

### ISSUE THREAD

**Issue by stanleyyuenyiu** [ryandrewjohnson/react-localize-redux#85] opened 2018-06-11 05:03 UTC
Assume 3 Languages, each language contains 600 translations

Assume 10 pages, each page avg using 30 unique translations

Step 1: navigate to each page (using react Route)
Step 2: switch lang after visited all pages
 
Excepted result: execute time within 500ms 

Actual Result: execute time >=7000ms 

Additional 
execute time will be within 300ms, if translations less than 200

**Comment by ryandrewjohnson** [comment] 2018-06-11 12:38
Can you create an example that reproduces the slowness in codesandbox?

**Comment by thchia** [comment] 2018-06-13 04:39
This caught my attention because some time back I encountered a related issue. If I was navigating from (say) one page to another (using react-router), there would be a noticeable delay between clicking the `Link` and the subsequent page rendering.

I avoided it at the time by disabling the default translate option, but this is obviously 1) a workaround and 2) not addressing the underlying issue.

I have attempted some basic profiling, not something I have done a lot but the results are revealing. A culprit appears to be the `.reduce` call in `getTranslationsForLanguage`. When I swapped this with a `for ... in` loop, the times dropped dramatically.

### Original implementation:
<img width="658" alt="rlr-reduce" src="https://user-images.githubusercontent.com/21194045/41330457-2f3da462-6f06-11e8-9dc1-7a9339ecf4cb.png">

### with `for ... in`:
<img width="586" alt="rlr-for-in" src="https://user-images.githubusercontent.com/21194045/41330479-56371bd4-6f06-11e8-9af5-b5e7c8b55e9d.png">

Both cases run from a fresh mount of the app into the DOM (i.e. after browser refresh).

@ryandrewjohnson  I don't really have the bandwidth to set up a load testing, so maybe we can publish a beta/canary/rc for @stanleyyuenyiu to test out?

**Comment by ryandrewjohnson** [comment] 2018-06-13 16:33
@thchia interesting findings. I just did some JSPerf tests to confirm the array.reduce vs for-loop speeds, and it looks like you're right. When acting on a low count of records the array.reduce outperforms the forloop. But crank up the record count and the reverse is true, which is showing in your tests.

At least with this arbitrary test it's showing a HUGE diff when the list.length gets high.

### With `list.length = 10000`
![image](https://user-images.githubusercontent.com/3419547/41364748-8735e5b8-6f05-11e8-98c7-8b6810569210.png)

### With `list.length = 100`
![image](https://user-images.githubusercontent.com/3419547/41364800-b5eedfe0-6f05-11e8-8c0b-cb9c6d557ce9.png)

Here's the link to the test in case you want to play around.
https://jsperf.com/array-reduce-test-ryan/1

**Comment by stanleyyuenyiu** [comment] 2018-06-14 07:55
Thanks for the sharing, but as the case of using this plugin, it doesnt pass our standard, therefore, we change to use react context directly, where no delay, and all translate request within 200ms for >600 translation keys

here is my sharing

LanguageProvider:

`import React from "react";
import { connect } from 'react-redux';
import get from 'lodash/get'

const LanguageContext = React.createContext();
export const LanguageConsumer = LanguageContext.Consumer;

export const getTranslate = (locale) => (id, data) => {

    if (!locale)
        locale = window.initialState.languages.default

    const fullId = locale + '.' + id;
    let text = get(window.i18n, fullId);

    if (text === undefined)
        return 'Missing translation for key `' + id + '`';

    for (let prop in data) {
        const pattern = '\\${\\s*' + prop + '\\s*}';
        const regex = new RegExp(pattern, 'gmi');
        text = text.replace(regex, data[prop]);
    }

    return text;
}

class LanguageProvider extends React.Component
{
    constructor(props) {
        super(props);

        this.state = {
            available: window.initialState.languages.available,
            active: window.initialState.languages.default
        }

        this.translate = this.translate.bind(this);
    }

    componentWillReceiveProps(nextProps) {
        if (this.props.locale !== nextProps.locale) {
            this.setState({active: nextProps.locale});
        }

    }

    translate(id, data) {

        const translate = getTranslate(this.state.active);

        return translate(id, data);
    }

    render() {
        return (
            <LanguageContext.Provider
                value={{
                    activeLanguage: this.state.active,
                    setActiveLanguage: this.setActiveLanguage,
                    availableLanguages: this.state.available,
                    translate: this.translate
                }}
            >
                {this.props.children}
            </LanguageContext.Provider>
        )
    }
}


const mapStateToProps = state => ({ locale: state.lang.locale });

export default connect(mapStateToProps)(LanguageProvider)`

app.js for the react root

`
/**
 * First we will load all of this project's JavaScript dependencies which
 * includes React and other helpers. It's a great starting point while
 * building robust, powerful web applications using React + Laravel.
 */

require('./bootstrap');

/**
 * Next, we will create a fresh React component instance and attach it to
 * the page. Then, you may begin adding components to this application
 * or customize the JavaScript scaffolding to fit your unique needs.
 */
import React from 'react';
import { render } from 'react-dom';
import "babel-polyfill";
import App from 'Components/App';
import { BrowserRouter as Router } from "react-router-dom";
import { Provider } from 'react-redux';
import LanguageProvider from 'Providers/LanguageProvider';
import configureStore from 'Store/configureStore'

const store = configureStore();


render(
    <Provider store={store}>
        <LanguageProvider>
            <Router>
                <App/>
            </Router>
        </LanguageProvider>
    </Provider>,
    document.getElementById('root')
);

`

**Comment by ryandrewjohnson** [comment] 2018-06-15 02:20
I have created a PR to start tracking the work on these performance improvements. #92

**Comment by stanleyyuenyiu** [comment] 2018-06-15 07:17
will check next week

**Comment by ryandrewjohnson** [comment] 2018-06-18 01:40
Fixed in #92.

**Comment by ryandrewjohnson** [comment] 2018-06-18 01:48
@stanleyyuenyiu I've just published a new version `v3.1.1` that has the performance improvement fixes. If you could give it a try when you get a chance, and let me know if it improves any of the issues you were having that'd be greatly appreciated.

**Comment by ryandrewjohnson** [comment] 2018-06-23 03:39
Closing this due to inactivity. Please re-open if issue persists.

**Closed by ryandrewjohnson** 2018-06-23 03:39 UTC
Labels: enhancement

**Comment by hashithkarunarathne** [comment] 2018-10-03 04:09
@ryandrewjohnson 
In my app it have 3 Languages, each language contains more than 2000 translations (and still growing).
I loaded the selected language translations on the App.js while loading time when the translations get increasing it took more time to load the App

**Comment by ryandrewjohnson** [comment] 2018-10-17 18:18
If you can provide a code sandbox with an example I can have a look.
