### ISSUE TITLE
Is there a way to get a string instead of an object (component) as a translation product?

### ISSUE THREAD

**Issue by zannix** [ryandrewjohnson/react-localize-redux#149] opened 2019-02-14 10:46 UTC
Is there a way to get a string instead of an object (component) as a translation product?

In my project I am using another component that expects a string prop (which would ideally be the translated string from react-localize-redux lib), and I don't know how to get that.

Edit: If it helps, I am doing this outside render function, in a component helper function that doesn't return anything.

**Which versions of `react` and `react-localize-redux` are you using?**
6.4.1
3.5.2

**Comment by ryandrewjohnson** [comment] 2019-02-15 02:53
I'm going to need some more detail to help you out. Ideally a working example in codesandbox, or at the very least a code snippet I can look at.

**Comment by vladmarton** [comment] 2019-03-22 11:34
Hey, great plugin!
I have a problem, im trying to insert <Translate> into a form placeholder but all it returns is:

[object Object]

`<Form.Control
                      type="tel"
                      placeholder={
                        <Translate id="frontpage.section7.form.placeholder-telephone" />
                      }
                      required
                    />`

**Comment by raheelkhan** [comment] 2019-03-26 17:05
I am also looking for the same.
I have a case where i have a input field element. The placeholder attribute of input field needs to be translated. 

```
let placeHolder = <Translate id="myPlaceHolder" />;
<Input placeholder={placeHolder} /> // yeilds [object Object]
```

**Comment by ryandrewjohnson** [comment] 2019-03-27 17:46
Duplicate of #145

**Closed by ryandrewjohnson** 2019-03-27 17:46 UTC
